[2022-04-09 22:33:51 +0000] [76145] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:8000']
  backlog: 2048
  workers: 1
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /root/rpcmeter/rpcmeter
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: gunicorn_error.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: rpcmeter.wsgi:application
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f70ea692ca0>
  on_reload: <function OnReload.on_reload at 0x7f70ea692dc0>
  when_ready: <function WhenReady.when_ready at 0x7f70ea692ee0>
  pre_fork: <function Prefork.pre_fork at 0x7f70ea6a9040>
  post_fork: <function Postfork.post_fork at 0x7f70ea6a9160>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f70ea6a9280>
  worker_int: <function WorkerInt.worker_int at 0x7f70ea6a93a0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f70ea6a94c0>
  pre_exec: <function PreExec.pre_exec at 0x7f70ea6a95e0>
  pre_request: <function PreRequest.pre_request at 0x7f70ea6a9700>
  post_request: <function PostRequest.post_request at 0x7f70ea6a9790>
  child_exit: <function ChildExit.child_exit at 0x7f70ea6a98b0>
  worker_exit: <function WorkerExit.worker_exit at 0x7f70ea6a99d0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f70ea6a9af0>
  on_exit: <function OnExit.on_exit at 0x7f70ea6a9c10>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2022-04-09 22:33:51 +0000] [76145] [INFO] Starting gunicorn 20.1.0
[2022-04-09 22:33:51 +0000] [76145] [DEBUG] Arbiter booted
[2022-04-09 22:33:51 +0000] [76145] [INFO] Listening at: http://0.0.0.0:8000 (76145)
[2022-04-09 22:33:51 +0000] [76145] [INFO] Using worker: sync
[2022-04-09 22:33:51 +0000] [76146] [INFO] Booting worker with pid: 76146
[2022-04-09 22:33:51 +0000] [76146] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rpcmeter'
[2022-04-09 22:33:51 +0000] [76146] [INFO] Worker exiting (pid: 76146)
[2022-04-09 22:33:51 +0000] [76145] [DEBUG] 1 workers
[2022-04-09 22:33:51 +0000] [76145] [INFO] Shutting down: Master
[2022-04-09 22:33:51 +0000] [76145] [INFO] Reason: Worker failed to boot.
[2022-04-09 22:34:43 +0000] [76161] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:8000']
  backlog: 2048
  workers: 1
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /root/rpcmeter/rpcmeter
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: gunicorn_error.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: rpcmeter.wsgi:application
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f1f2f8b7ca0>
  on_reload: <function OnReload.on_reload at 0x7f1f2f8b7dc0>
  when_ready: <function WhenReady.when_ready at 0x7f1f2f8b7ee0>
  pre_fork: <function Prefork.pre_fork at 0x7f1f2f8ce040>
  post_fork: <function Postfork.post_fork at 0x7f1f2f8ce160>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f1f2f8ce280>
  worker_int: <function WorkerInt.worker_int at 0x7f1f2f8ce3a0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f1f2f8ce4c0>
  pre_exec: <function PreExec.pre_exec at 0x7f1f2f8ce5e0>
  pre_request: <function PreRequest.pre_request at 0x7f1f2f8ce700>
  post_request: <function PostRequest.post_request at 0x7f1f2f8ce790>
  child_exit: <function ChildExit.child_exit at 0x7f1f2f8ce8b0>
  worker_exit: <function WorkerExit.worker_exit at 0x7f1f2f8ce9d0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f1f2f8ceaf0>
  on_exit: <function OnExit.on_exit at 0x7f1f2f8cec10>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2022-04-09 22:34:43 +0000] [76161] [INFO] Starting gunicorn 20.1.0
[2022-04-09 22:34:43 +0000] [76161] [DEBUG] Arbiter booted
[2022-04-09 22:34:43 +0000] [76161] [INFO] Listening at: http://0.0.0.0:8000 (76161)
[2022-04-09 22:34:43 +0000] [76161] [INFO] Using worker: sync
[2022-04-09 22:34:43 +0000] [76162] [INFO] Booting worker with pid: 76162
[2022-04-09 22:34:43 +0000] [76162] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rpcmeter'
[2022-04-09 22:34:43 +0000] [76162] [INFO] Worker exiting (pid: 76162)
[2022-04-09 22:34:43 +0000] [76161] [INFO] Shutting down: Master
[2022-04-09 22:34:43 +0000] [76161] [INFO] Reason: Worker failed to boot.
